name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      release_title:
        type: string
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.release_title }} ${{ github.event.inputs.version }}"
