name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      release_title:
        type: string
        required: true
      release_text:
        type: string
        required: false

jobs:
  compile-job:
    uses: ./.github/workflows/compile_pdf.yml
    secrets: inherit
    
  release:
    needs: compile-job
    runs-on: ubuntu-latest

    steps:
    - name: Download Build results
      uses: actions/download-artifact@v8
      with:
        name: full-pdf
        
    - name: Download multipage 2x2 long edge
      uses: actions/download-artifact@v8
      with:
        name: cards-2x2-longedge-pdf
        
    - name: Download multipage 2x2 short edge
      uses: actions/download-artifact@v8
      with:
        name: cards-2x2-shortedge-pdf
        
    - name: Download multipage 3x3 long edge
      uses: actions/download-artifact@v8
      with:
        name: cards-3x3-longedge-pdf
        
    - name: Download multipage 3x3 short edge
      uses: actions/download-artifact@v8
      with:
        name: cards-3x3-shortedge-pdf

    - name: Download multipage 4x4 long edge
      uses: actions/download-artifact@v8
      with:
        name: cards-4x4-longedge-pdf
        
    - name: Download multipage 4x4 short edge
      uses: actions/download-artifact@v8
      with:
        name: cards-4x4-shortedge-pdf
    
    # Download the single cards
    - uses: actions/download-artifact@v8
      with:
        name: Tanzanleitungen-einzeln
        path: Tanzanleitungen-einzeln/

    - name: Zip the single files
      run: zip -r Tanzanleitungen-einzeln.zip Tanzanleitungen-einzeln
      
    - name: get file listing
      run: ls -la .
      
    - name: Send greeting
      run: echo "${{ github.event.inputs.release_title }} ${{ github.event.inputs.version }}"
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        name: "${{ github.event.inputs.release_title }}"
        tag_name: "${{ github.event.inputs.version }}"
        make_latest: true  # TODO change to true when everything works
        fail_on_unmatched_files: true
        body: "${{ github.event.inputs.release_text }}"
        files: |
          Tanzanleitungen.pdf
          Tanzanleitungen-einzeln.zip
          Tanzanleitungen_*.pdf

          
        #Tanzanleitungen_2x2_A6_lange_Kante.pdf
        #Tanzanleitungen_2x2_A6_kurze_Kante.pdf
        #Tanzanleitungen_3x3_A7_lange_Kante.pdf
        #Tanzanleitungen_3x3_A7_kurze_Kante.pdf
        #Tanzanleitungen_4x4_A8_lange_Kante.pdf
        #Tanzanleitungen_4x4_A8_kurze_Kante.pdf

