name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      release_title:
        type: string
        required: true

jobs:
  compile-job:
    uses: ./.github/workflows/compile_pdf.yml
    secrets: inherit
    
  release:
    needs: compile-job
    runs-on: ubuntu-latest

    steps:
    - name: Download Build results
      uses: actions/download-artifact@v8
      with:
        name: full-pdf
    - name: get file listing
      run: ls -la .
      
    - name: Send greeting
      run: echo "${{ github.event.inputs.release_title }} ${{ github.event.inputs.version }}"
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        name: "${{ github.event.inputs.release_title }}"
        tag_name: "${{ github.event.inputs.version }}"
        make_latest: false  # TODO change to true when everything works
        fail_on_unmatched_files: true
        files: Tanzanleitung.pdf
